name: Check Test

on: [ pull_request ]

jobs:
  test:
    name: ✓ Tests and Coverage-Report
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_hg.backend.apikey: dummy_value

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Set up JDK temurin:17
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🏃 Run tests and do coverage report
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean :sdk:koverXmlReport

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/sdk/build/reports/kover/report.xml
          token: ${{ secrets.REPO_WRITE_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 80
          debug-mode: false
          title: Code Coverage Report
          update-comment: true

      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"